import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppLayout } from "@/features/layout/AppLayout";

import { ThemeEffect } from "@/features/settings/components/logic/ThemeEffect";
import { DensityEffect } from "@/features/settings/components/logic/DensityEffect";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased select-none`}>
        <ThemeEffect />
        <DensityEffect />
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
